country_capitals = {
    "Afghanistan": "Kabul",
    "Albania": "Tirana",
    "Argentina": "Buenos Aires",
    "Australia": "Canberra",
    "Austria": "Vienna",
    "Bangladesh": "Dhaka",
    "Belgium": "Brussels",
    "Brazil": "Brasília",
    "Canada": "Ottawa",
    "Chile": "Santiago",
    "China": "Beijing",
    "Colombia": "Bogotá",
    "Czech Republic": "Prague",
    "Denmark": "Copenhagen",
    "Ecuador": "Quito",
    "Egypt": "Cairo",
    "Finland": "Helsinki",
    "France": "Paris",
    "Germany": "Berlin",
    "Greece": "Athens",
    "Hungary": "Budapest",
    "India": "New Delhi",
    "Indonesia": "Jakarta",
    "Iran": "Tehran",
    "Iraq": "Baghdad",
    "Ireland": "Dublin",
    "Israel": "Jerusalem",
    "Italy": "Rome",
    "Japan": "Tokyo",
    "Jordan": "Amman",
    "Kazakhstan": "Nur-Sultan",
    "Kuwait": "Kuwait City",
    "Lebanon": "Beirut",
    "Malaysia": "Kuala Lumpur",
    "Mexico": "Mexico City",
    "Netherlands": "Amsterdam",
    "New Zealand": "Wellington",
    "Norway": "Oslo",
    "Pakistan": "Islamabad",
    "Peru": "Lima",
    "Philippines": "Manila",
    "Poland": "Warsaw",
    "Portugal": "Lisbon",
    "Qatar": "Doha",
    "Russia": "Moscow",
    "Saudi Arabia": "Riyadh",
    "Singapore": "Singapore",
    "South Korea": "Seoul",
    "Spain": "Madrid",
    "Sweden": "Stockholm",
    "Switzerland": "Bern",
    "Taiwan": "Taipei",
    "Thailand": "Bangkok",
    "Turkey": "Ankara",
    "Ukraine": "Kyiv",
    "United Arab Emirates": "Abu Dhabi",
    "United Kingdom": "London",
    "United States": "Washington, D.C.",
    "Venezuela": "Caracas",
    "Vietnam": "Hanoi"
}
